version: '3.8'

volumes:
  kafka_data:
  zookeeper_data:

networks:
  kafka-secure-net:

services:

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=no
      - ZOO_ENABLE_AUTH=yes
      - ZOO_SERVER_USERS=zoo_admin
      - ZOO_SERVER_PASSWORDS=adminpassword
    volumes:
      - zookeeper_data:/bitnami/zookeeper
    networks:
      - kafka-secure-net

  kafka:
    image: bitnami/kafka:3.4
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=SASL_PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=SASL_PLAINTEXT:SASL_PLAINTEXT
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_CLIENT_USERS=kafkaclient
      - KAFKA_CLIENT_PASSWORDS=kafkasecret
      - KAFKA_INTER_BROKER_USER=kafkaclient
      - KAFKA_INTER_BROKER_PASSWORD=kafkasecret
      - ALLOW_PLAINTEXT_LISTENER=no
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - kafka-secure-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "9091:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      - KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=SASL_PLAINTEXT
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM=PLAIN
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="kafkaclient" password="kafkasecret";
      - KAFKA_UI_AUTH_TYPE=basic
      - KAFKA_UI_AUTH_USER=kafka_admin
      - KAFKA_UI_AUTH_PASS=adminui
    depends_on:
      - kafka
    networks:
      - kafka-secure-net
