server:
  port: 80
  shutdown: graceful
spring:
  kafka:
    admin.auto-create: false
    admin.properties.request.timeout.ms: 60000
    bootstrap-servers: localhost:9092
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: PLAIN
      sasl.jaas.config: >
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="kafkaclient"
        password="kafkasecret";

logging:
  level:
    org.apache.kafka: DEBUG